trigger: none
pr: none
schedules:
- cron: 0 20 * * *
  branches:
    include: [ master ]

jobs:
- job: linux
  pool: nni-it-1es-11
  timeoutInMinutes: 60

  steps:

  - script: |
      sudo apt-get -o DPkg::Lock::Timeout=120 --fix-broken install
    displayName: (GPU) Fix broken dependencies

  - script: |
      wget -O install-snoopy.sh https://github.com/a2o/snoopy/raw/install/install/install-snoopy.sh &&
      chmod 755 install-snoopy.sh &&
      sudo ./install-snoopy.sh stable
    displayName: Install Snoopy

  - script: |
      cat /lib/systemd/system/apt-daily.timer
      sudo ls /var/spool/cron/crontabs
      ls /etc/apt/apt.conf.d
      cat /etc/apt/apt.conf.d/*
      cat /etc/crontab
      crontab -l
      nvidia-smi
    displayName: Check GPU status

  # - template: templates/install-dependencies.yml
  #   parameters:
  #     platform: ubuntu-latest-gpu
  #     python_env: venv

  # - template: templates/install-nni.yml

  # - template: templates/install-customized-tuner.yml

  - script: |
      METRIC_OUTPUT_DIR=. python -m nni.tools.gpu_tool.gpu_metrics_collector
    displayName: Debug

  - script: |
      sudo cat /var/log/auth.log
    displayName: Show log

  # - script: |
  #     cd test
  #     python training_service/nnitest/run_tests.py --config training_service/config/integration_tests.yml --ts local
  #   displayName: Integration test

  # - template: templates/save-crashed-info.yml
  #   parameters:
  #     training_service: local
