trigger: none
pr: none
schedules:
- cron: 0 20 * * *
  branches:
    include: [ master ]

jobs:
- job: linux
  pool: nni-it-1es-11
  timeoutInMinutes: 60

  steps:

  # https://askubuntu.com/questions/1038923/do-i-really-need-apt-daily-service-and-apt-daily-upgrade-service
  - script: |
      set -e
      set -x
      sudo systemctl list-units
      sudo systemctl list-timers
      sudo systemctl disable apt-daily.service
      sudo systemctl disable apt-daily.timer
      sudo systemctl disable apt-daily-upgrade.timer
      sudo systemctl disable apt-daily-upgrade.service
      sudo systemctl list-units
      sudo systemctl list-timers
      sudo apt-get -o DPkg::Lock::Timeout=120 --fix-broken -y install
    displayName: (GPU) Fix broken dependencies

  - script: |
      wget -O install-snoopy.sh https://github.com/a2o/snoopy/raw/install/install/install-snoopy.sh &&
      chmod 755 install-snoopy.sh &&
      sudo ./install-snoopy.sh stable
    displayName: Install Snoopy

  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.9
    displayName: Configure Python version

  - script: |
      python -m pip install pip==22.0.4 setuptools==62.1.0 wheel==0.37.1
    displayName: Install PyPA tools

  - script: |
      python -m pip install -r dependencies/required.txt
    displayName: Install dependencies

  - script: |
      cat /lib/systemd/system/apt-daily.timer
      sudo ls /var/spool/cron/crontabs
      ls /etc/apt/apt.conf.d
      cat /etc/apt/apt.conf.d/*
      cat /etc/crontab
      crontab -l
      nvidia-smi
    displayName: Check GPU status

  # - template: templates/install-dependencies.yml
  #   parameters:
  #     platform: ubuntu-latest-gpu
  #     python_env: venv

  # - template: templates/install-nni.yml

  # - template: templates/install-customized-tuner.yml

  - script: |
      METRIC_OUTPUT_DIR=. python -m nni.tools.gpu_tool.gpu_metrics_collector
    displayName: Debug

  - script: |
      sudo systemctl list-units
      sudo systemctl list-timers
    displayName: Show service

  - script: |
      sudo cat /var/log/auth.log
    displayName: Show log

  # - script: |
  #     cd test
  #     python training_service/nnitest/run_tests.py --config training_service/config/integration_tests.yml --ts local
  #   displayName: Integration test

  # - template: templates/save-crashed-info.yml
  #   parameters:
  #     training_service: local
